language: cpp
compiler:
# - clang
  - gcc
cache:
  directories:
    - $HOME/cmake
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - openssl
    - gcc-4.9
    - g++-4.9
install:
  - 'export CC=gcc-4.9'
  - 'export CXX=g++-4.9'
  - 'mkdir $HOME/prefix'
  - 'if [ ! -f $HOME/cmake/bootstrap ]; then git clone git://cmake.org/cmake.git --branch v3.3.1 --single-branch --depth 1 $HOME/cmake && cd $HOME/cmake && ./bootstrap --prefix=$HOME/prefix --parallel=4; fi'
  - 'cd $HOME/cmake && make -j4 && make install'
script:
  - 'cd $TRAVIS_BUILD_DIR'
  - 'mkdir build && cd build'
  - 'PATH=$HOME/prefix/bin:$PATH cmake .. && make && make check'
