language: cpp
compiler:
# - clang
  - gcc
cache: ccache
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - openssl
    - gcc-4.8
    - g++-4.8
install:
  - 'export CC=/usr/bin/gcc-4.8'
  - 'export CXX=/usr/bin/g++-4.8'
  - 'mkdir $HOME/prefix'
  - 'cd $HOME && git clone git://cmake.org/cmake.git --branch v3.3.1 --single-branch --depth 1 && cd cmake && ./bootstrap --prefix=$HOME/prefix --enable-ccache --parallel=4 && make -j4 && make install'
script: 'PATH=$HOME/prefix/bin:$PATH cmake . && make && make check'
