language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
    - openssl
install:
  - 'mkdir prefix'
  - 'git clone git://cmake.org/cmake.git --branch v3.3.1 --single-branch --depth 1 && cd cmake && ./bootstrap --prefix=../prefix && make && make install; cd ..'
script: 'PATH=prefix:$PATH cmake . && make && make check'
